name: Upload to Google Drive
on:
  push:
    branches:
      - resume

jobs:
  upload-to-google-drive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_KEY }}
          filename: "src/myresume.pdf"
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: "resume_chishengliu.pdf"
          overwrite: "true"
